### ISSUE TITLE
Error in Moodle 2.4.3

### ISSUE THREAD

**Issue by gbyram** [oohoo/moodle-block_course_search#1]
Error reading from database

More information about this error
Debug info: Unknown column 'mdl_tab.intro' in 'field list'
SELECT mdl_tab_content.id as tabcontentid, mdl_tab.id as id,mdl_tab.name, mdl_tab.intro, mdl_tab.course, mdl_tab_content.tabname, mdl_tab_content.tabcontent
FROM mdl_tab_content
INNER JOIN mdl_tab ON mdl_tab_content.tabid = mdl_tab.id AND mdl_tab.course = ?
WHERE mdl_tab.name LIKE ? OR mdl_tab.intro LIKE ?
OR mdl_tab_content.tabname LIKE ? OR mdl_tab_content.tabcontent LIKE ?
[array (
0 => 1,
1 => '%lookup%',
2 => '%lookup%',
3 => '%lookup%',
4 => '%lookup%',
)]
Error code: dmlreadexception
Stack trace:

```
line 426 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 1023 of \lib\dml\mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 196 of \blocks\course_search\lib.php: call to mysqli_native_moodle_database->get_records_sql()
line ? of unknownfile: call to block_course_search_search_module_tab()
line 56 of \blocks\course_search\results.php: call to call_user_func()
```

**Comment by bretin** [comment]
Hi,

I think there is a problem with your table "mdl_tab" because this table should have the field "intro". 
Could you give me the version of the plugin resource "Tab Display" ?

Thanks,

Nicolas

**Comment by gbyram** [comment]
Tab display (mod_tab)  2012021400

  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `course` bigint(10) NOT NULL DEFAULT '0',
  `name` varchar(255) DEFAULT NULL,
  `css` longtext,
  `menucss` longtext,
  `displaymenu` tinyint(1) NOT NULL DEFAULT '0',
  `menuname` varchar(255) DEFAULT NULL,
  `taborder` smallint(4) NOT NULL DEFAULT '1',
  `legacyfiles` smallint(4) NOT NULL DEFAULT '0',
  `legacyfileslast` bigint(10) DEFAULT NULL,
  `timemodified` bigint(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `mdl_tab_cou_ix` (`course`)

**Comment by bretin** [comment]
Hi,

You should update your version of the tab display.
We are currently on the version 2013072200. It is why you have no "intro" field.
Please update it and let me now if it resolves your problem.
Thanks,

Nicolas

**Comment by gbyram** [comment]
Thanks. I'll start the ball rolling to get mod_tab 2013072200 (released 23 July 2013) installed. Unfortunately on the corporate system I use, there is an approval process which takes at least a month before a new release can be included in the code.
PS. It is a shame the code is not backward compatible (e.g. check what fields are available in the plugins that will be searched before running the search query).
