### ISSUE TITLE
Incorrect sql syntax in lib.php (postgresql)

### ISSUE THREAD

**Issue by PeloNZ** [oohoo/moodle-block_course_search#2]
This error consistently occurs with the latest version of Moodle 2.4.
Using postgres 9.1

Debug info: ERROR: argument of OR must be type boolean, not type integer
LINE 1: SELECT \* FROM mdl_assign WHERE course=$1 AND (0 OR name LIK...
^

``` sql
SELECT * FROM mdl_assign WHERE course=$1 AND (0 OR name LIKE $2 OR intro LIKE $3)
[array (
0 => 1,
1 => '%test%',
2 => '%test%',
)]
```

Error code: dmlreadexception

``` php
Stack trace:
line 426 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 753 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 72 of /blocks/course_search/lib.php: call to pgsql_native_moodle_database->get_records_sql()
line 60 of /blocks/course_search/results.php: call to block_course_search_search_module()
```

Postgres specific fix:

diff --git a/blocks/course_search/lib.php b/blocks/course_search/lib.php
index 5a1aac1..7ce837d 100644
--- a/blocks/course_search/lib.php
+++ b/blocks/course_search/lib.php
@@ -31,7 +31,7 @@ function block_course_search_search_module($courseid, $module, $q)
     global $CFG, $DB, $OUTPUT;

``` php
     $ret = '';
-    $sqlWere = 'course=? AND (0';
+    $sqlWere = 'course=? AND (false';
     $sqlParams = array($courseid);
     //At least one search field is needed
     $onefield = false;
```

**Comment by bretin** [comment]
Hi,

Thanks for the info, I tested on MySQL with "(false" instead of "(0" and it works too.
I pushed the patch on Github and Moodle.org

Thanks,

Nicolas
